// Antag Tickets System Defines
#define DEFAULT_ANTAG_TICKETS 10.0

// Configuration flags for antag ticket visibility
#define ANTAG_TICKETS_SHOW_READIED_PLAYERS		(1<<0)
#define ANTAG_TICKETS_SHOW_ROUNDS_SINCE_ANTAG	(1<<1)
#define ANTAG_TICKETS_SHOW_TICKET_COUNT			(1<<2)
#define ANTAG_TICKETS_SHOW_PRECISE_ODDS			(1<<3)

// Default configuration - show all information
#define ANTAG_TICKETS_DEFAULT_CONFIG (ANTAG_TICKETS_SHOW_READIED_PLAYERS|ANTAG_TICKETS_SHOW_ROUNDS_SINCE_ANTAG|ANTAG_TICKETS_SHOW_TICKET_COUNT|ANTAG_TICKETS_SHOW_PRECISE_ODDS)
